// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import OnboardingWizardController from "./onboarding_wizard_controller"
application.register("onboarding-wizard", OnboardingWizardController)

import SortableDomainsController from "./sortable_domains_controller"
application.register("sortable-domains", SortableDomainsController)
